version: '3.8'
services:
  paises:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - service-net-app
    restart: on-failure

networks:
  service-net-app:
